[package]
name = "hollow-render"
version = "0.17.0"
edition = "2021"
description = "Fast software rasterizer and egui primitive compositing engine for Hollow Canvas"

[lib]
test = false

[dependencies]
hollow-core = { path = "../hollow-core", version = "0.17.0" }
egui = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
