[package]
name = "hollow-render"
version = "0.13.1"
edition = "2021"
description = "Fast software rasterizer, pixel compositor, and egui primitive backend for Hollow Canvas"

[lib]
test = false

[dependencies]
hollow-core = { path = "../hollow-core", version = "0.13.1" }
egui = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
